// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResmapApi.Models;

#nullable disable

namespace ResmapApi.Migrations
{
    [DbContext(typeof(ResmapdbContext))]
    [Migration("20260903202214_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResmapApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07EF6FC8E5");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Categorias_Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ResmapApi.Models.DetalleSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioReferencial")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitudPedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DetalleS__3214EC0721B555A8");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SolicitudPedidoId");

                    b.ToTable("DetalleSolicitud", (string)null);
                });

            modelBuilder.Entity("ResmapApi.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Producto__3214EC0703B206C4");

                    b.HasIndex("CategoriaId");

                    b.HasIndex(new[] { "Codigo" }, "UQ_Productos_Codigo")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ResmapApi.Models.Proveedore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Proveedo__3214EC07EFC6177B");

                    b.HasIndex(new[] { "Email" }, "UQ_Proveedores_Email")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("ResmapApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07067E1288");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Roles_Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ResmapApi.Models.SolicitudesPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Solicitu__3214EC07ED6D2DF8");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitudesPedido", (string)null);
                });

            modelBuilder.Entity("ResmapApi.Models.SolicitudesProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitudPedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Solicitu__3214EC077C431110");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("SolicitudPedidoId");

                    b.ToTable("SolicitudesProveedor", (string)null);
                });

            modelBuilder.Entity("ResmapApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Rut")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC07D4F04259");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Email" }, "UQ_Usuarios_Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ResmapApi.Models.DetalleSolicitud", b =>
                {
                    b.HasOne("ResmapApi.Models.Producto", "Producto")
                        .WithMany("DetalleSolicituds")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleSolicitud_Producto");

                    b.HasOne("ResmapApi.Models.SolicitudesPedido", "SolicitudPedido")
                        .WithMany("DetalleSolicituds")
                        .HasForeignKey("SolicitudPedidoId")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleSolicitud_Solicitud");

                    b.Navigation("Producto");

                    b.Navigation("SolicitudPedido");
                });

            modelBuilder.Entity("ResmapApi.Models.Producto", b =>
                {
                    b.HasOne("ResmapApi.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Categorias");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ResmapApi.Models.SolicitudesPedido", b =>
                {
                    b.HasOne("ResmapApi.Models.Usuario", "Usuario")
                        .WithMany("SolicitudesPedidos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_SolicitudesPedido_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ResmapApi.Models.SolicitudesProveedor", b =>
                {
                    b.HasOne("ResmapApi.Models.Proveedore", "Proveedor")
                        .WithMany("SolicitudesProveedors")
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK_SolicitudesProveedor_Proveedor");

                    b.HasOne("ResmapApi.Models.SolicitudesPedido", "SolicitudPedido")
                        .WithMany("SolicitudesProveedors")
                        .HasForeignKey("SolicitudPedidoId")
                        .IsRequired()
                        .HasConstraintName("FK_SolicitudesProveedor_SolicitudPedido");

                    b.Navigation("Proveedor");

                    b.Navigation("SolicitudPedido");
                });

            modelBuilder.Entity("ResmapApi.Models.Usuario", b =>
                {
                    b.HasOne("ResmapApi.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Roles");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ResmapApi.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ResmapApi.Models.Producto", b =>
                {
                    b.Navigation("DetalleSolicituds");
                });

            modelBuilder.Entity("ResmapApi.Models.Proveedore", b =>
                {
                    b.Navigation("SolicitudesProveedors");
                });

            modelBuilder.Entity("ResmapApi.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ResmapApi.Models.SolicitudesPedido", b =>
                {
                    b.Navigation("DetalleSolicituds");

                    b.Navigation("SolicitudesProveedors");
                });

            modelBuilder.Entity("ResmapApi.Models.Usuario", b =>
                {
                    b.Navigation("SolicitudesPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
